'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowRight, BarChart3, BookOpen, Boxes, Check, ChevronRight, CircleDot, Command, ExternalLink, FileText, GitBranch, HelpCircle, Map, MapPin, Network, Plus, Search, Shield, Users, Wrench, X } from 'lucide-react';

const projects = [
  { id: 'PRJ-000001', name: 'Airborne Communications Relay', unit: 'Fictional Unit Alpha', maturity: 'Field Tested', progress: 72, status: 'Active', tone: 'green' },
  { id: 'PRJ-000004', name: 'Directional Ground Antenna System', unit: 'Fictional Unit Delta', maturity: 'Prototype', progress: 48, status: 'Active', tone: 'blue' },
  { id: 'PRJ-000008', name: 'Alternative Control Link', unit: 'Fictional Unit Bravo', maturity: 'Validated', progress: 91, status: 'Transitioning', tone: 'purple' },
];

const nav = [['Dashboard', BarChart3], ['Explore', Search], ['Problems', AlertTriangle], ['Projects', Wrench], ['Units', Users], ['Map', Map], ['Capability Graph', Network], ['Activity', Activity]] as const;

export function Portal() {
  const [query, setQuery] = useState('');
  const [active, setActive] = useState('Dashboard');
  const [creating, setCreating] = useState(false);
  const [created, setCreated] = useState<{id:string,title:string}[]>([]);
  const matches = useMemo(() => query.trim() ? [
    { type: 'Problem', id: 'PRB-000001', title: 'Short RF Range', meta: '4 active approaches · 6 units' },
    { type: 'Project', id: 'PRJ-000001', title: 'Airborne Communications Relay', meta: 'Field Tested · Unit Alpha' },
    { type: 'Capability', id: 'TAG', title: 'RF / Communications', meta: '12 related records' },
  ].filter(x => `${x.id} ${x.title} ${x.meta}`.toLowerCase().includes(query.toLowerCase()) || query.toLowerCase() === 'rf') : [], [query]);

  useEffect(() => {
    const stored = localStorage.getItem('forge-problems');
    if (stored) setTimeout(() => {
      try { setCreated(JSON.parse(stored)); } catch { setCreated([]); }
    }, 0);
    const context = (document as Document & {modelContext?: {registerTool:(tool:unknown, options?:unknown)=>unknown}}).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    void Promise.resolve(context.registerTool({name:'start_problem_creation',title:'Start problem creation',description:'Open the visible form used to create a new capability problem.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{setCreating(true);return {status:'form_opened'}}},{signal:lifecycle.signal})).catch(()=>{});
    return () => lifecycle.abort();
  }, []);

  const saveProblem = (title:string) => {
    const item={id:`PRB-${String(13+created.length).padStart(6,'0')}`,title};
    const next=[item,...created]; setCreated(next); localStorage.setItem('forge-problems',JSON.stringify(next)); setCreating(false); setActive('Problems');
  };

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark"><Shield size={18}/></span><div><strong>FORGE</strong><small>UAS Capability Portal</small></div></div>
      <nav aria-label="Primary navigation">{nav.map(([label, Icon]) => <button key={label} className={active === label ? 'nav-item active' : 'nav-item'} onClick={() => setActive(label)}><Icon size={17}/><span>{label}</span>{label === 'Problems' && <em>12</em>}</button>)}</nav>
      <div className="sidebar-foot"><div className="classification">FICTIONAL DATA</div><button className="nav-item"><HelpCircle size={17}/> Help & guidance</button><div className="profile"><span>PA</span><div><strong>Portal Analyst</strong><small>Contributor</small></div></div></div>
    </aside>
    <main>
      <header className="topbar"><div className="search-wrap"><Search size={18}/><input aria-label="Global search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search problems, projects, units, lessons…"/><kbd><Command size={11}/> K</kbd>{query && <div className="search-results"><div className="result-label">Best matches</div>{matches.map(m => <button key={m.id} onClick={() => {setActive(m.type==='Project'?'Project':m.type==='Problem'?'Problem':'Explore');setQuery('')}}><span className="result-icon">{m.type[0]}</span><div><strong>{m.id} — {m.title}</strong><small>{m.type} · {m.meta}</small></div><ArrowRight size={15}/></button>)}</div>}</div><button className="create" onClick={()=>setCreating(true)}><Plus size={16}/> Create</button></header>
      <div className="page"><View active={active} setActive={setActive} created={created}/></div>
    </main>
    {creating && <CreateModal onClose={()=>setCreating(false)} onSave={saveProblem}/>} 
  </div>;
}

function View({active,setActive,created}:{active:string,setActive:(v:string)=>void,created:{id:string,title:string}[]}){
  if(active==='Problem') return <ProblemView onCompare={()=>setActive('Compare')} onProject={()=>setActive('Project')}/>;
  if(active==='Compare') return <CompareView/>;
  if(active==='Project') return <ProjectView onUnit={()=>setActive('Unit')} onRelated={()=>setActive('Explore')}/>;
  if(active==='Unit'||active==='Units') return <UnitView onMap={()=>setActive('Map')}/>;
  if(active==='Map') return <MapView onProject={()=>setActive('Project')}/>;
  if(active==='Capability Graph') return <GraphView onProblem={()=>setActive('Problem')}/>;
  if(active==='Projects') return <ProjectsView onProject={()=>setActive('Project')}/>;
  if(active==='Problems') return <ProblemsView created={created} onProblem={()=>setActive('Problem')}/>;
  if(active==='Explore') return <ExploreView onProject={()=>setActive('Project')}/>;
  if(active==='Activity') return <ActivityView/>;
  return <Dashboard/>;
}

function Dashboard() {
  return <><div className="page-head"><div><p className="eyebrow">MONDAY · 07 SEPTEMBER 2026</p><h1>Capability development overview</h1><p>See where work is moving, where teams overlap, and where support is needed.</p></div><button className="secondary"><Activity size={16}/> View activity</button></div>
    <section className="stat-grid"><Stat icon={<AlertTriangle/>} tone="amber" label="Open Problems" value="12" note="4 without validated solution"/><Stat icon={<Wrench/>} tone="blue" label="Active Projects" value="14" note="+3 updated this week"/><Stat icon={<Users/>} tone="violet" label="Participating Units" value="12" note="Across 8 locations"/><Stat icon={<CircleDot/>} tone="green" label="Validated Solutions" value="6" note="2 ready to transition"/></section>
    <div className="dashboard-grid"><section className="panel span-2"><PanelHead title="Current capability activity" note="Most active problem spaces across the network" action="View all problems"/><div className="problem-list"><ProblemRow priority="HIGH" title="PRB-000001 · Short RF Range" meta="4 projects · 6 units · RF / Communications" updated="Updated 2h ago"/><ProblemRow priority="HIGH" title="PRB-000002 · Video Link Degradation in Complex Terrain" meta="3 projects · 4 units · Video" updated="Updated 5h ago"/><ProblemRow priority="MED" title="PRB-000003 · Navigation Reliability in Degraded Environments" meta="3 projects · 5 units · Navigation" updated="Yesterday"/></div></section>
      <section className="panel"><div className="panel-head"><div><h2>Projects needing help</h2><p>Open assistance requests</p></div><span className="count">3</span></div><Help icon={<Boxes/>} title="Alternative Control Link" text="Seeking spectrum analysis support" meta="Unit Bravo · 4 days ago"/><Help icon={<GitBranch/>} title="Common GCS Adapter" text="Needs integration test partner" meta="Unit Echo · 6 days ago"/></section>
      <section className="panel span-2"><PanelHead title="Recently updated projects" note="Progress worth reviewing" action="View all projects"/><div className="project-cards">{projects.map(p => <div className="project-card" key={p.id}><div><span className={`dot ${p.tone}`}/><small>{p.status}</small></div><strong>{p.name}</strong><p>{p.id} · {p.unit}</p><Progress value={p.progress}/><footer><span>{p.maturity}</span><b>{p.progress}%</b></footer></div>)}</div></section>
      <section className="panel"><PanelHead title="Network pulse" note="Last 7 days"/><div className="pulse"><div><strong>28</strong><span>Updates</span></div><div><strong>7</strong><span>Lessons</span></div><div><strong>5</strong><span>Tests</span></div></div><div className="spark" aria-label="Activity trend">{[25,38,32,66,54,86,72].map(n=><i key={n} style={{height:`${n}%`}}/>)}</div></section></div></>;
}

function Stat({icon,tone,label,value,note}:{icon:React.ReactNode,tone:string,label:string,value:string,note:string}){return <article><span className={`icon ${tone}`}>{icon}</span><div><small>{label}</small><strong>{value}</strong><p>{note}</p></div></article>}
function PanelHead({title,note,action}:{title:string,note:string,action?:string}){return <div className="panel-head"><div><h2>{title}</h2><p>{note}</p></div>{action&&<button>{action} <ChevronRight size={15}/></button>}</div>}
function ProblemRow({priority,title,meta,updated}:{priority:string,title:string,meta:string,updated:string}){return <button className="problem-row"><span className={`priority ${priority==='MED'?'med':'high'}`}>{priority}</span><div><strong>{title}</strong><small>{meta}</small></div><span className="updated">{updated}</span><ChevronRight size={17}/></button>}
function Help({icon,title,text,meta}:{icon:React.ReactNode,title:string,text:string,meta:string}){return <div className="help-card"><span>{icon}</span><div><strong>{title}</strong><p>{text}</p><small>{meta}</small></div></div>}
function Progress({value}:{value:number}){return <div className="progress"><span style={{width:`${value}%`}}/></div>}

function ProblemView({onCompare,onProject}:{onCompare:()=>void,onProject:()=>void}) {
  const all = projects.concat([{ id:'PRJ-000013', name:'Networked Communications Architecture', unit:'Fictional Unit Foxtrot', maturity:'Concept', progress:22,status:'Planning',tone:'amber'}]);
  return <><div className="crumb">Problems <ChevronRight size={14}/> PRB-000001</div><div className="problem-hero"><div><span className="priority high">HIGH PRIORITY</span><h1>Short RF Range</h1><p>PRB-000001 · RF / Communications · Reported by 6 units</p></div><button className="create" onClick={onCompare}><BarChart3 size={16}/> Compare 4 projects</button></div><div className="question-callout"><strong>What is happening?</strong><p>Teams operating in complex terrain report control and video links losing reliability before mission-relevant distances. Four parallel approaches are being tested across the network.</p></div><h2 className="section-title">Projects addressing this problem <span>4</span></h2><div className="approach-grid">{all.map(p=><article key={p.id}><div><span className={`dot ${p.tone}`}/><small>{p.status}</small><span className="maturity">{p.maturity}</span></div><h3>{p.name}</h3><p>{p.id} · {p.unit}</p><Progress value={p.progress}/><footer><small>Completion</small><strong>{p.progress}%</strong></footer><button onClick={onProject}>Open project <ArrowRight size={15}/></button></article>)}</div></>;
}

function CompareView() {
  return <><div className="crumb">Problems <ChevronRight size={14}/> PRB-000001 <ChevronRight size={14}/> Compare</div><div className="page-head"><div><p className="eyebrow">PROJECT COMPARISON</p><h1>Approaches to Short RF Range</h1><p>Compare maturity, tradeoffs, test evidence, and outcomes side-by-side.</p></div></div><div className="comparison"><table><thead><tr><th>Approach</th>{projects.map(p=><th key={p.id}><small>{p.id}</small><strong>{p.name}</strong></th>)}</tr></thead><tbody><tr><th>Lead unit</th>{projects.map(p=><td key={p.id}>{p.unit}</td>)}</tr><tr><th>Maturity</th>{projects.map(p=><td key={p.id}><span className="maturity">{p.maturity}</span></td>)}</tr><tr><th>Completion</th>{projects.map(p=><td key={p.id}><b>{p.progress}%</b><Progress value={p.progress}/></td>)}</tr><tr><th>Key advantage</th><td>Extends connectivity around terrain limitations.</td><td>High gain without an extra airborne node.</td><td>Strong resilience and cross-platform potential.</td></tr><tr><th>Key limitation</th><td>Requires an additional airborne node.</td><td>Pointing and setup time burden operators.</td><td>Requires compatible radios and approvals.</td></tr><tr><th>Latest result</th><td><span className="outcome good">Successful field test</span></td><td><span className="outcome">Range improved 38%</span></td><td><span className="outcome good">Validated at two sites</span></td></tr></tbody></table></div></>;
}

function ProjectView({onUnit,onRelated}:{onUnit:()=>void,onRelated:()=>void}){
  const [technical,setTechnical]=useState(false);
  return <><div className="crumb">Projects <ChevronRight size={14}/> PRJ-000001</div><div className="project-title"><div><div className="status-line"><span className="dot green"/> Active <span className="maturity">Field Tested</span></div><h1>Airborne Communications Relay</h1><p>PRJ-000001 · Last updated 2 hours ago</p></div><div className="view-toggle"><button className={!technical?'selected':''} onClick={()=>setTechnical(false)}>Executive</button><button className={technical?'selected':''} onClick={()=>setTechnical(true)}>Technical</button></div></div>
    {!technical?<div className="detail-grid"><section className="panel hero-summary"><p className="eyebrow">EXECUTIVE SUMMARY</p><h2>Extending resilient connectivity around terrain limitations</h2><p>Unit Alpha is field-testing an airborne relay node that restores control and video links when direct line-of-sight is blocked. Two field events have shown repeatable range improvement.</p><div className="summary-metrics"><div><strong>72%</strong><span>Complete</span></div><div><strong>2</strong><span>Field tests</span></div><div><strong>6.4 km</strong><span>Best link</span></div></div></section><section className="panel"><h2>Ownership & participation</h2><button className="unit-link" onClick={onUnit}><span>FA</span><div><strong>Fictional Unit Alpha</strong><small>Lead unit · Ridgeview, CO</small></div><ChevronRight/></button><p className="mini-label">SUPPORTING UNITS</p><p>Unit Bravo · Unit Charlie</p></section><section className="panel"><h2>Problems addressed</h2><div className="linked-record"><AlertTriangle/><div><strong>PRB-000001 · Short RF Range</strong><small>Primary problem</small></div></div><div className="linked-record"><AlertTriangle/><div><strong>PRB-000002 · Video Link Degradation</strong><small>Related problem</small></div></div><button className="text-action" onClick={onRelated}>Explore related work <ArrowRight/></button></section><section className="panel"><h2>Latest result</h2><span className="outcome good"><Check/> Successful field test</span><p className="body-copy">Relay maintained a stable link behind a terrain mask across three repeat runs. Operator setup time remains the largest constraint.</p></section></div>:<TechnicalView/>}
  </>;
}

function TechnicalView(){return <div className="detail-grid"><section className="panel span-2"><PanelHead title="Project phases" note="Evidence and decisions across the lifecycle"/><div className="timeline"><Timeline title="Phase 1 · Bench integration" meta="Complete · 14 May 2026" text="Integrated relay payload, power system, and control-link radios."/><Timeline title="Phase 2 · Controlled range test" meta="Complete · 02 July 2026" text="Confirmed 4.8 km link with clear line-of-sight."/><Timeline title="Phase 3 · Complex terrain field test" meta="In progress · 05 September 2026" text="Stable link achieved behind terrain mask; setup time requires refinement."/></div></section><section className="panel"><h2>Technical artifacts</h2><Artifact icon={<GitBranch/>} title="relay-node" meta="Repository · updated 3d ago"/><Artifact icon={<FileText/>} title="Field Test Plan v2.1" meta="PDF · 1.8 MB"/><Artifact icon={<FileText/>} title="Integration Notes" meta="Markdown · 42 KB"/></section><section className="panel"><h2>Lessons learned</h2><div className="lesson"><BookOpen/><div><strong>Mounting position affects link stability</strong><p>Airframe shadowing was more significant than predicted. Elevated mounting improved consistency.</p></div></div><div className="lesson caution"><BookOpen/><div><strong>Setup workflow is too complex</strong><p>Operators need a guided pre-flight checklist and clearer health indicators.</p></div></div></section></div>}
function Timeline({title,meta,text}:{title:string,meta:string,text:string}){return <div className="timeline-item"><span/><div><strong>{title}</strong><small>{meta}</small><p>{text}</p></div></div>}
function Artifact({icon,title,meta}:{icon:React.ReactNode,title:string,meta:string}){return <div className="artifact"><span>{icon}</span><div><strong>{title}</strong><small>{meta}</small></div><ExternalLink/></div>}

function UnitView({onMap}:{onMap:()=>void}){return <><div className="crumb">Units <ChevronRight size={14}/> Fictional Unit Alpha</div><div className="problem-hero"><div className="unit-heading"><span>FA</span><div><p className="eyebrow">CAPABILITY DEVELOPMENT UNIT</p><h1>Fictional Unit Alpha</h1><p>Ridgeview, Colorado · 18 contributors</p></div></div><button className="secondary" onClick={onMap}><MapPin/> View on map</button></div><div className="detail-grid"><section className="panel span-2"><PanelHead title="Current portfolio" note="5 active projects across 4 capability areas"/><div className="project-cards">{projects.map(p=><button className="project-card clickable" key={p.id}><span className="maturity">{p.maturity}</span><strong>{p.name}</strong><p>{p.id} · {p.progress}% complete</p><Progress value={p.progress}/></button>)}</div></section><section className="panel"><h2>Capability strengths</h2><div className="tag-cloud"><span>RF / Communications</span><span>Networking</span><span>Payloads</span><span>Field Testing</span></div></section><section className="panel"><h2>Recent lessons</h2><p className="body-copy"><b>7 lessons</b> published this quarter, including relay mounting, power budgeting, and operator setup.</p></section></div></>}

function ProjectsView({onProject}:{onProject:()=>void}){const [maturity,setMaturity]=useState('All');return <><ListHead title="Projects" note="20 connected solution efforts"/><div className="filterbar"><Search/><input placeholder="Filter projects…"/><select value={maturity} onChange={e=>setMaturity(e.target.value)}><option>All</option><option>Field Tested</option><option>Validated</option><option>Prototype</option></select><select><option>All capabilities</option><option>RF / Communications</option><option>Navigation</option></select><select><option>All locations</option><option>Ridgeview, CO</option><option>Northpoint, VA</option></select></div><div className="list-table">{projects.filter(p=>maturity==='All'||p.maturity===maturity).map(p=><button key={p.id} onClick={onProject}><span><small>{p.id}</small><strong>{p.name}</strong></span><span>{p.unit}</span><span className="maturity">{p.maturity}</span><span><Progress value={p.progress}/><b>{p.progress}%</b></span><ChevronRight/></button>)}</div></>}
function ProblemsView({created,onProblem}:{created:{id:string,title:string}[],onProblem:()=>void}){const base=[{id:'PRB-000001',title:'Short RF Range'},{id:'PRB-000002',title:'Video Link Degradation in Complex Terrain'},{id:'PRB-000003',title:'Navigation Reliability in Degraded Environments'}];return <><ListHead title="Problems" note={`${12+created.length} enduring capability gaps`}/><div className="list-table">{[...created,...base].map((p,i)=><button key={p.id} onClick={onProblem}><span className={`priority ${i<2?'high':'med'}`}>{i<2?'HIGH':'MED'}</span><span><small>{p.id}</small><strong>{p.title}</strong></span><span>{i===0?'4 projects · 6 units':'3 projects · 4 units'}</span><ChevronRight/></button>)}</div></>}
function ListHead({title,note}:{title:string,note:string}){return <div className="page-head"><div><p className="eyebrow">KNOWLEDGE BASE</p><h1>{title}</h1><p>{note}</p></div></div>}

function MapView({onProject}:{onProject:()=>void}){return <><ListHead title="Capability map" note="Explore expertise and project activity geographically"/><div className="map-panel"><div className="map-controls"><strong>8 locations</strong><input placeholder="Search locations…"/><label><input type="checkbox" defaultChecked/> Active projects</label><label><input type="checkbox" defaultChecked/> Units</label><label><input type="checkbox"/> Help requests</label></div><div className="map-canvas"><div className="terrain t1"/><div className="terrain t2"/><button className="map-pin p1"><span>5</span><small>Ridgeview, CO</small></button><button className="map-pin p2" onClick={onProject}><span>3</span><small>Northpoint, VA</small></button><button className="map-pin p3"><span>2</span><small>Red Mesa, AZ</small></button><div className="map-note"><MapPin/><div><strong>Fictional Unit Alpha</strong><small>5 projects · RF, Networking, Payloads</small></div></div></div></div></>}
function GraphView({onProblem}:{onProblem:()=>void}){return <><ListHead title="Capability Graph" note="Trace how problems connect to projects, units, technologies, and outcomes"/><div className="graph-panel"><button className="node problem" onClick={onProblem}><AlertTriangle/>Short RF Range<small>Problem</small></button><span className="edge e1"/><button className="node project"><Wrench/>Airborne Relay<small>Project</small></button><span className="edge e2"/><button className="node unit"><Users/>Unit Alpha<small>Lead unit</small></button><span className="edge e3"/><button className="node tech"><Network/>Relay Node<small>Technology</small></button><span className="edge e4"/><button className="node lesson"><BookOpen/>Mounting lesson<small>Lesson learned</small></button><span className="edge e5"/><button className="node outcome"><Check/>Successful test<small>Outcome</small></button></div></>}
function ExploreView({onProject}:{onProject:()=>void}){return <><ListHead title="Related work" note="Connections you may not have discovered through direct links"/><div className="question-callout"><strong>Why these results?</strong><p>Matched through shared RF / Communications capabilities, participating units, locations, and lessons learned.</p></div><div className="approach-grid">{projects.map(p=><article key={p.id}><span className="maturity">82% related</span><h3>{p.name}</h3><p>{p.unit} · RF / Communications</p><button onClick={onProject}>Review connection <ArrowRight/></button></article>)}</div></>}
function ActivityView(){return <><ListHead title="Recent activity" note="40+ events across the capability network"/><section className="panel activity-feed">{['Field test result added to Airborne Communications Relay','Lesson learned published by Fictional Unit Alpha','Assistance requested for Alternative Control Link','Project phase completed on Directional Ground Antenna System','Repository link added to Common GCS Adapter'].map((x,i)=><div key={x}><span><Activity/></span><div><strong>{x}</strong><small>{i+2} hours ago · Portal Analyst</small></div></div>)}</section></>}

function CreateModal({onClose,onSave}:{onClose:()=>void,onSave:(title:string)=>void}){const [title,setTitle]=useState('');const related=title.toLowerCase().includes('rf')||title.toLowerCase().includes('range');return <div className="modal-backdrop" role="presentation"><form className="modal" onSubmit={e=>{e.preventDefault();if(title.trim())onSave(title.trim())}}><button className="modal-x" type="button" onClick={onClose}><X/></button><p className="eyebrow">NEW RECORD</p><h2>Create capability problem</h2><p>Capture an enduring gap before proposing a solution.</p><label>Problem title<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Short RF Range"/></label><label>Description<textarea required placeholder="What is happening, who is affected, and why does it matter?"/></label>{related&&<div className="possible"><strong>Possible existing work</strong><p><b>PRB-000001 · Short RF Range</b><br/>4 projects · 6 units · 91% title match</p><button type="button">Open existing problem</button></div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="create">Create problem</button></div></form></div>}
