ALTER TABLE "ActivityEvent" ADD COLUMN "subjectUserId" INTEGER REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "HelpRequest" ADD COLUMN "contactUserId" INTEGER REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "HelpRequest" ADD COLUMN "followsProjectLead" BOOLEAN NOT NULL DEFAULT true;
